fn result() ! {
    return Error("simple error");
}

fn result2() ! {
    return Error("simple error (returned: {}, idx: {})".fmt(true, 0));
}

fn result3() !i32 {
    return 5;
}

let RESULT_VALUE: i32 = result3().!;

test "propagate result in `let` declaration" {
    @assert(RESULT_VALUE == 5);
}

test "catch result error" {
    result() catch |err| {
        @assert(err is Error);
        @assert(err.msg == "simple error");
    };

    result2() catch |err2| {
        @assert(err2 is Error);
        @assert(err2.msg == "simple error (returned: true, idx: 0)");
    };
}
